//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B1Rec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public int numri_i_fatures { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<double> totali_i_fatures { get; set; }
        public Nullable<double> baker { get; set; }
        public Nullable<double> mesing { get; set; }
        public Nullable<double> alumin { get; set; }
        public Nullable<double> plumb { get; set; }
        public Nullable<double> rosfaj { get; set; }
        public Nullable<double> kanaqe { get; set; }
        public Nullable<double> akumulator { get; set; }
        public Nullable<double> hekur { get; set; }
        public Nullable<double> shishe { get; set; }
        public Nullable<double> qese { get; set; }
        public string shitesi { get; set; }
    }
}
