//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B1Rec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blerjet
    {
        public int id { get; set; }
        public string Shitesi { get; set; }
        public Nullable<decimal> Shuma { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Blersi { get; set; }
    }
}
