//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B1Rec
{
    using System;
    using System.Collections.Generic;
    
    public partial class pazariDitor
    {
        public int id { get; set; }
        public Nullable<decimal> Blerja { get; set; }
        public Nullable<decimal> Hyrja { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<decimal> Mbetja { get; set; }
    }
}
